# conda.yaml

name: nlu-env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch
  - cpuonly # Muy importante: le dice que instale la versión de PyTorch para CPU
  - pip:
    - mlflow
    - boto3
    - transformers
    - datasets
